services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: muhur_dev
    ports:
      - "5433:5432"
    volumes:
      - muhur_pgdata:/var/lib/postgresql/data

volumes:
  muhur_pgdata:
